pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  libboost:
    max_pin: x.x.x
ignore_build_only_deps:
- numpy
- python
extend_keys:
- ignore_version
- pin_run_as_build
- ignore_build_only_deps
- extend_keys
harfbuzz:
- '2.4'
cyrus_sasl:
- 2.1.26
pixman:
- '0.30'
tk:
- '8.6'
m2w64_c_compiler:
- m2w64-toolchain
lua:
- '5'
openjpeg:
- '2.3'
rust_compiler_version:
- 1.56.0
lzo:
- '2'
openssl:
- 1.1.1
proj4:
- 5.2.0
giflib:
- '5'
cross_compiler_target_platform:
- win-32
- win-64
glib:
- '2'
geos:
- 3.8.0
hdfeos5:
- '5.1'
mpfr:
- '4'
cpu_optimization_target:
- nocona
hdf4:
- '4.2'
xz:
- '5'
fortran_compiler_version:
- 2019.0.0
qtwebkit:
- 'true'
libxml2:
- '2.9'
proj:
- 6.2.1
mkl:
- '2021'
blas_impl:
- mkl
libnetcdf:
- '4.8'
gnu:
- 2.12.2
libtiff:
- '4.1'
gstreamer:
- '1.14'
cxx_compiler:
- vs2017
readline:
- '8.0'
fortran_compiler:
- intel-fortran
libwebp:
- 1.2.0
cran_mirror:
- https://mran.microsoft.com/snapshot/2018-01-01
m2w64_cxx_compiler:
- m2w64-toolchain
libffi:
- '3.4'
libgdal:
- '3.0'
clang_variant:
- clang
libpng:
- '1.6'
icu:
- '58'
sqlite:
- '3'
libxslt:
- '1.1'
bzip2:
- '1.0'
boost_cpp:
- '1.73'
llvm_variant:
- llvm
python_impl:
- cpython
libgsasl:
- '1.8'
VERBOSE_CM:
- VERBOSE=1
c_compiler:
- vs2017
hdfeos2:
- '2.20'
freetype:
- '2.10'
serf:
- 1.3.9
vc:
- '14'
m2w64_fortran_compiler:
- m2w64-toolchain
expat:
- '2.2'
python_implementation:
- cpython
zlib:
- '1.2'
libprotobuf:
- 3.11.2
perl:
- '5.26'
boost:
- '1.73'
rust_compiler:
- rust-gnu
- rust
libkml:
- '1.3'
libdap4:
- '3.19'
r_version:
- 3.5.0
target_platform:
- win-64
r_implementation:
- mro-base
- r-base
gst_plugins_base:
- '1.14'
libgd:
- 2.2.5
fontconfig:
- '2.13'
cairo:
- '1.14'
dbus:
- '1'
openblas:
- 0.3.3
VERBOSE_AT:
- V=1
r_base:
- '3.5'
hdf5:
- 1.10.6
channel_targets:
- defaults
apr:
- 1.6.3
jpeg:
- '9'
g2clib:
- '1.6'
gmp:
- '6.1'
numpy:
- '1.16'
python:
- '3.8'
zip_keys:
- - python
  - numpy
